// pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  geolocator: ^7.0.3
  http: ^0.13.3
  firebase_core: ^1.10.0
  firebase_auth: ^1.10.0
  cloud_firestore: ^2.3.0
  video_player: ^2.1.1
